//========= Copyright © 1996-2001, Valve LLC, All rights reserved. ============
//
// Purpose: 
//
// $NoKeywords: $
//=============================================================================

#include "glquake.h"
#include <stdlib.h>
#include <malloc.h>
#include <string.h>
#include "materialsystem/imaterialproxy.h"
#include "materialproxyfactory.h"

IMaterialProxy *CMaterialProxyFactory::CreateProxy( const char *proxyName )
{
#if !defined( SWDS )
	// assumes that the client.dll is already LoadLibraried
	CreateInterfaceFn clientFactory = Sys_GetFactory( "client" DLL_EXT_STRING );
	if( !clientFactory )
	{
		return NULL;
	}
	// allocate exactly enough memory for the versioned name on the stack.
	char *proxyVersionedName;
	proxyVersionedName = 
		( char * )_alloca( strlen( proxyName ) + 
		strlen( IMATERIAL_PROXY_INTERFACE_VERSION ) + 1 );
	strcpy( proxyVersionedName, proxyName );
	strcat( proxyVersionedName, IMATERIAL_PROXY_INTERFACE_VERSION );
	IMaterialProxy *materialProxy;
	materialProxy = ( IMaterialProxy * )clientFactory( proxyVersionedName, NULL );
	if( !materialProxy )
	{
		Con_DPrintf( "Can't find material proxy \"%s\"\n", proxyName );
		return NULL;
	}
	return materialProxy;
#else
	return NULL;
#endif
}

void CMaterialProxyFactory::DeleteProxy( IMaterialProxy *pProxy )
{
	// how do you delete something generated by an interface.h factory?
	if( pProxy )
	{
		pProxy->Release();
	}
}
