#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.12.589.0000
//
//   fxc /DLIGHT_COMBO=0 /DFOG_TYPE=0 /DNUM_BONES=2 /DBUMPMAP=1 /DVERTEXCOLOR=0
//    /DNORMALORTANGENTSPACE=1 /Dmain=main /Emain /Tvs_2_0 /nologo
//    /Fhout_fxctmp9_968_17096.h vertexlit_and_unlit_generic_vs20.fxc
//
//
// Parameters:
//
//   float4 cBaseTexCoordTransform[2];
//   float4 cDetailOrBumpTexCoordTransform[2];
//   float4 cEnvmapMaskTexCoordTransform[2];
//   float4 cEyePosWaterZ;
//   float4 cFogParams;
//   float4x3 cModel[16];
//   float4x4 cViewProj;
//
//
// Registers:
//
//   Name                           Reg   Size
//   ------------------------------ ----- ----
//   cEyePosWaterZ                  c2       1
//   cViewProj                      c8       4
//   cFogParams                     c16      1
//   cModel                         c42     48
//   cBaseTexCoordTransform         c90      2
//   cDetailOrBumpTexCoordTransform c92      2
//   cEnvmapMaskTexCoordTransform   c94      2
//

    vs_2_0
    def c1, 765.005859, 0, 0, 0
    dcl_position v0
    dcl_blendweight v1
    dcl_blendindices v2
    dcl_normal v3
    dcl_texcoord v4
    dcl_tangent v6
    mul r0.xy, v2.zyzw, c1.x
    mova a0.xy, r0
    mul r0, v1.y, c42[a0.y]
    mad r0, c42[a0.x], v1.x, r0
    dp3 r4.x, v3, r0
    mul r2, v1.y, c43[a0.y]
    mul r1, v1.y, c44[a0.y]
    mad r2, c43[a0.x], v1.x, r2
    mad r1, c44[a0.x], v1.x, r1
    dp3 r4.y, v3, r2
    dp3 r4.z, v3, r1
    dp3 r3.x, v6, r0
    dp4 r0.x, v0, r0
    dp3 r3.y, v6, r2
    dp3 r3.z, v6, r1
    dp4 r0.y, v0, r2
    mul r2.xyz, r4.zxyw, r3.yzxw
    dp4 r0.z, v0, r1
    mad r1.xyz, r4.yzxw, r3.zxyw, -r2
    mov oT6.xyz, r4
    mov oT4.xyz, r3
    mul oT5.xyz, r1, v6.w
    mov r0.w, c0.y
    dp4 oPos.x, r0, c8
    dp4 oPos.y, r0, c9
    dp4 oPos.w, r0, c11
    dp4 r1.y, r0, c10
    add oT3.xyz, -r0, c2
    mad oFog, -r1.y, c16.w, c16.x
    mov oPos.z, r1.y
    dp4 oT0.x, v4, c90
    dp4 oT0.y, v4, c91
    dp4 oT1.x, v4, c92
    dp4 oT1.y, v4, c93
    dp4 oT2.x, v4, c94
    dp4 oT2.y, v4, c95
    mov oD0, c0.x
    mov oD1.xyz, c0.x
    mov oT7.xyz, c0.x

// approximately 39 instruction slots used
#endif

const DWORD g_vs20_main[] =
{
    0xfffe0200, 0x006bfffe, 0x42415443, 0x0000001c, 0x00000173, 0xfffe0200, 
    0x00000007, 0x0000001c, 0x00000100, 0x0000016c, 0x000000a8, 0x005a0002, 
    0x00020002, 0x000000c0, 0x00000000, 0x000000d0, 0x005c0002, 0x00020002, 
    0x000000c0, 0x00000000, 0x000000ef, 0x005e0002, 0x00020002, 0x000000c0, 
    0x00000000, 0x0000010c, 0x00020002, 0x00020001, 0x0000011c, 0x00000000, 
    0x0000012c, 0x00100002, 0x00020001, 0x0000011c, 0x00000000, 0x00000137, 
    0x002a0002, 0x00020030, 0x00000140, 0x00000000, 0x00000150, 0x00080002, 
    0x00020004, 0x0000015c, 0x00000000, 0x73614263, 0x78655465, 0x726f6f43, 
    0x61725464, 0x6f66736e, 0xab006d72, 0x00030001, 0x00040001, 0x00000002, 
    0x00000000, 0x74654463, 0x4f6c6961, 0x6d754272, 0x78655470, 0x726f6f43, 
    0x61725464, 0x6f66736e, 0x63006d72, 0x6d766e45, 0x614d7061, 0x65546b73, 
    0x6f6f4378, 0x72546472, 0x66736e61, 0x006d726f, 0x65794563, 0x57736f50, 
    0x72657461, 0xabab005a, 0x00030001, 0x00040001, 0x00000001, 0x00000000, 
    0x676f4663, 0x61726150, 0x6300736d, 0x65646f4d, 0xabab006c, 0x00030003, 
    0x00030004, 0x00000010, 0x00000000, 0x65695663, 0x6f725077, 0xabab006a, 
    0x00030003, 0x00040004, 0x00000001, 0x00000000, 0x325f7376, 0x4d00305f, 
    0x6f726369, 0x74666f73, 0x29522820, 0x44334420, 0x53203958, 0x65646168, 
    0x6f432072, 0x6c69706d, 0x39207265, 0x2e32312e, 0x2e393835, 0x30303030, 
    0xababab00, 0x05000051, 0xa00f0001, 0x443f4060, 0x00000000, 0x00000000, 
    0x00000000, 0x0200001f, 0x80000000, 0x900f0000, 0x0200001f, 0x80000001, 
    0x900f0001, 0x0200001f, 0x80000002, 0x900f0002, 0x0200001f, 0x80000003, 
    0x900f0003, 0x0200001f, 0x80000005, 0x900f0004, 0x0200001f, 0x80000006, 
    0x900f0006, 0x03000005, 0x80030000, 0x90e60002, 0xa0000001, 0x0200002e, 
    0xb0030000, 0x80e40000, 0x04000005, 0x800f0000, 0x90550001, 0xa0e4202a, 
    0xb0550000, 0x05000004, 0x800f0000, 0xa0e4202a, 0xb0000000, 0x90000001, 
    0x80e40000, 0x03000008, 0x80010004, 0x90e40003, 0x80e40000, 0x04000005, 
    0x800f0002, 0x90550001, 0xa0e4202b, 0xb0550000, 0x04000005, 0x800f0001, 
    0x90550001, 0xa0e4202c, 0xb0550000, 0x05000004, 0x800f0002, 0xa0e4202b, 
    0xb0000000, 0x90000001, 0x80e40002, 0x05000004, 0x800f0001, 0xa0e4202c, 
    0xb0000000, 0x90000001, 0x80e40001, 0x03000008, 0x80020004, 0x90e40003, 
    0x80e40002, 0x03000008, 0x80040004, 0x90e40003, 0x80e40001, 0x03000008, 
    0x80010003, 0x90e40006, 0x80e40000, 0x03000009, 0x80010000, 0x90e40000, 
    0x80e40000, 0x03000008, 0x80020003, 0x90e40006, 0x80e40002, 0x03000008, 
    0x80040003, 0x90e40006, 0x80e40001, 0x03000009, 0x80020000, 0x90e40000, 
    0x80e40002, 0x03000005, 0x80070002, 0x80d20004, 0x80c90003, 0x03000009, 
    0x80040000, 0x90e40000, 0x80e40001, 0x04000004, 0x80070001, 0x80c90004, 
    0x80d20003, 0x81e40002, 0x02000001, 0xe0070006, 0x80e40004, 0x02000001, 
    0xe0070004, 0x80e40003, 0x03000005, 0xe0070005, 0x80e40001, 0x90ff0006, 
    0x02000001, 0x80080000, 0xa0550000, 0x03000009, 0xc0010000, 0x80e40000, 
    0xa0e40008, 0x03000009, 0xc0020000, 0x80e40000, 0xa0e40009, 0x03000009, 
    0xc0080000, 0x80e40000, 0xa0e4000b, 0x03000009, 0x80020001, 0x80e40000, 
    0xa0e4000a, 0x03000002, 0xe0070003, 0x81e40000, 0xa0e40002, 0x04000004, 
    0xc00f0001, 0x81550001, 0xa0ff0010, 0xa0000010, 0x02000001, 0xc0040000, 
    0x80550001, 0x03000009, 0xe0010000, 0x90e40004, 0xa0e4005a, 0x03000009, 
    0xe0020000, 0x90e40004, 0xa0e4005b, 0x03000009, 0xe0010001, 0x90e40004, 
    0xa0e4005c, 0x03000009, 0xe0020001, 0x90e40004, 0xa0e4005d, 0x03000009, 
    0xe0010002, 0x90e40004, 0xa0e4005e, 0x03000009, 0xe0020002, 0x90e40004, 
    0xa0e4005f, 0x02000001, 0xd00f0000, 0xa0000000, 0x02000001, 0xd0070001, 
    0xa0000000, 0x02000001, 0xe0070007, 0xa0000000, 0x0000ffff
};
