include_guard( GLOBAL )

set( CLIENT_BASE_SOURCE_FILES )
BEGIN_SRC( CLIENT_BASE_SOURCE_FILES "Source Files" )
	SRC_GRP(
		SOURCES
		#{
			"${SRCDIR}/game_shared/activitylist.cpp"
			"${SRCDIR}/game_shared/ammodef.cpp"
			"${SRCDIR}/game_shared/animation.cpp"
			"${SRCDIR}/game_shared/basecombatcharacter_shared.cpp"
			"${SRCDIR}/game_shared/basecombatweapon_shared.cpp"
			"${SRCDIR}/game_shared/baseentity_shared.cpp"
			"${SRCDIR}/game_shared/basegrenade_shared.cpp"
			"${SRCDIR}/game_shared/baseparticleentity.cpp"
			"${SRCDIR}/game_shared/baseplayer_shared.cpp"
			"${SRCDIR}/game_shared/baseviewmodel_shared.cpp"
			"${SRCDIR}/game_shared/beam_shared.cpp"
			"${SRCDIR}/game_shared/bone_setup.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/collisionproperty.cpp"
			"${SRCDIR}/game_shared/decals.cpp"
			"${SRCDIR}/game_shared/effect_dispatch_data.cpp"
			"${SRCDIR}/game_shared/ehandle.cpp"
			"${SRCDIR}/game_shared/entitylist_base.cpp"
			"${SRCDIR}/game_shared/env_wind_shared.cpp"
			"${SRCDIR}/game_shared/gamemovement.cpp" # Precomp: ?????
			"${SRCDIR}/game_shared/gamerules.cpp"
			"${SRCDIR}/game_shared/gamestringpool.cpp"
			"${SRCDIR}/game_shared/gamevars_shared.cpp"
			"${SRCDIR}/game_shared/igamesystem.cpp"
			"${SRCDIR}/game_shared/interval.cpp"
			"${SRCDIR}/game_shared/movevars_shared.cpp"
			"${SRCDIR}/game_shared/multiplay_gamerules.cpp"
			"${SRCDIR}/game_shared/physics_main_shared.cpp"
			"${SRCDIR}/game_shared/physics_saverestore.cpp"
			"${SRCDIR}/game_shared/physics_shared.cpp"
			"${SRCDIR}/game_shared/precache_register.cpp"
			"${SRCDIR}/game_shared/predictableid.cpp"
			"${SRCDIR}/game_shared/predictioncopy.cpp"
			"${SRCDIR}/game_shared/ragdoll_shared.cpp"
			"${SRCDIR}/game_shared/rope_helpers.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/saverestore.cpp"
			"${SRCDIR}/game_shared/sheetsimulator.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/singleplay_gamerules.cpp"
			"${SRCDIR}/game_shared/SoundEmitterSystem.cpp"
			"${SRCDIR}/game_shared/SoundEmitterSystemBase.cpp"
			"${SRCDIR}/game_shared/soundenvelope.cpp"
			"${SRCDIR}/game_shared/sprite.cpp"
			"${SRCDIR}/game_shared/SpriteTrail.cpp"
			"${SRCDIR}/game_shared/takedamageinfo.cpp"
			"${SRCDIR}/game_shared/test_ehandle.cpp"
			"${SRCDIR}/game_shared/usermessages.cpp"
			"${SRCDIR}/game_shared/util_shared.cpp"
			"${SRCDIR}/game_shared/voice_banmgr.cpp"
			"${SRCDIR}/game_shared/voice_status.cpp"
			"${SRCDIR}/game_shared/weapon_parse.cpp"
			"${SRCDIR}/game_shared/weapon_parse_default.cpp" # !CSTRIKE

			"${SRCDIR}/public/bitbuf.cpp" # Noprecomp?
			"${SRCDIR}/public/characterset.cpp" # Noprecomp?
			"${SRCDIR}/public/checksum_crc.cpp" # Noprecomp?
			"${SRCDIR}/public/client_class.cpp" # Noprecomp?
			"${SRCDIR}/public/collisionutils.cpp" # Noprecomp?
			"${SRCDIR}/public/convar.cpp" # Noprecomp?
			"${SRCDIR}/public/crtmemdebug.cpp" # Noprecomp?
			"${SRCDIR}/public/dt_recv.cpp" # Noprecomp?
			"${SRCDIR}/public/filesystem_helpers.cpp" # Noprecomp?
			"${SRCDIR}/public/imageloader.cpp" # Noprecomp?
			"${SRCDIR}/public/interface.cpp" # Noprecomp?
			"${SRCDIR}/public/mathlib.cpp" # Noprecomp?
			"${SRCDIR}/public/measure_section.cpp" # Noprecomp?
			"${SRCDIR}/public/mempool.cpp" # Noprecomp?
			"${SRCDIR}/public/mem_fgets.cpp" # Noprecomp?
			"${SRCDIR}/public/networkvar.cpp" # Noprecomp?
			"${SRCDIR}/public/rope_physics.cpp" # Noprecomp?
			"${SRCDIR}/public/sentence.cpp" # Noprecomp?
			"${SRCDIR}/public/simple_physics.cpp" # Noprecomp?
			"${SRCDIR}/public/stringpool.cpp"
			"${SRCDIR}/public/stringregistry.cpp" # Noprecomp?
			"${SRCDIR}/public/tgaloader.cpp" # Noprecomp?
			"${SRCDIR}/public/tier0/memoverride.cpp" # Noprecomp?
			"${SRCDIR}/public/UserCmd.cpp"
			"${SRCDIR}/public/utlbuffer.cpp" # Noprecomp?
			"${SRCDIR}/public/utlsymbol.cpp" # Noprecomp?
			"${SRCDIR}/public/vallocator.cpp" # Noprecomp?
			"${SRCDIR}/public/vmatrix.cpp" # Noprecomp?

			"alphamaterialproxy.cpp"
			"animatedentitytextureproxy.cpp"
			"animatedtextureproxy.cpp"
			"baseanimatedtextureproxy.cpp"
			"BaseModViewport.cpp" # !TF2 && !HL1 && !HL2
			"beamdraw.cpp"
			"camomaterialproxy.cpp"
			"cdll_client_int.cpp"
			"cdll_util.cpp"
			"classmap.cpp"
			"clienteffectprecachesystem.cpp"
			"cliententitylist.cpp"
			"clientleafsystem.cpp"
			"clientmode_shared.cpp"
			"clientshadowmgr.cpp"
			"clientsideeffects.cpp"
			"clientsideeffects_test.cpp"
			"client_thinklist.cpp"
			"c_ai_basehumanoid.cpp"
			"c_ai_basenpc.cpp"
			"c_baseanimating.cpp"
			"c_baseanimatingoverlay.cpp"
			"c_basecombatcharacter.cpp"
			"c_basecombatweapon.cpp"
			"c_basedoor.cpp"
			"c_baseentity.cpp"
			"c_baseflex.cpp"
			"c_basenetworkable.cpp"
			"c_baseplayer.cpp"
			"c_baseviewmodel.cpp"
			"c_breakableprop.cpp"
			"c_clientstats.cpp"
			"c_dynamiclight.cpp"
			"c_env_screenoverlay.cpp"
			"c_fire_smoke.cpp"
			"c_func_areaportalwindow.cpp"
			"c_func_breakablesurf.cpp"
			"c_func_conveyor.cpp"
			"c_func_dust.cpp"
			"c_func_lod.cpp"
			"c_func_occluder.cpp"
			"c_func_smokevolume.cpp"
			"c_gib.cpp"
			"c_hairball.cpp"
			"c_lightglow.cpp"
			"c_physbox.cpp"
			"c_physicsprop.cpp"
			"c_plasma.cpp"
			"c_playerresource.cpp"
			"c_props.cpp"
			"c_prop_vehicle.cpp"
			"c_recipientfilter.cpp"
			"c_rope.cpp"
			"c_shadowcontrol.cpp"
			"c_soundscape.cpp"
			"c_sprite.cpp"
			"c_sun.cpp"
			"c_team.cpp"
			"c_terrainmodmgr.cpp"
			"c_testtraceline.cpp"
			"c_test_proxytoggle.cpp"
			"c_user_message_register.cpp"
			"c_vguiscreen.cpp"
			"c_world.cpp"
			"death.cpp" # !CSTRIKE && !TF2
			"detailobjectsystem.cpp"
			"dummyproxy.cpp"
			"EffectsClient.cpp"
			"functionproxy.cpp"
			"fx_blood.cpp"
			"fx_cube.cpp"
			"fx_explosion.cpp"
			"fx_fleck.cpp"
			"fx_impact.cpp"
			"fx_quad.cpp"
			"fx_shelleject.cpp"
			"fx_staticline.cpp"
			"fx_tracer.cpp"
			"fx_water.cpp"
			"gametrace_client.cpp"
			"geiger.cpp"
			"glow_overlay.cpp"
			"history_resource.cpp"
			"hud.cpp"
			"hud_animationinfo.cpp"
			"hud_chat.cpp"
			"hud_closecaption.cpp"
			"hud_crosshair.cpp"
			"hud_element_helper.cpp"
			"hud_msg.cpp"
			"hud_numericdisplay.cpp" # !TF2
			"hud_pdump.cpp"
			"hud_redraw.cpp"
			"hud_vehicle.cpp"
			"hud_weapon.cpp"
			"initializer.cpp"
			"in_camera.cpp"
			"in_joystick.cpp" # Noprecomp?
			"in_main.cpp"
			"in_mouse.cpp" # Noprecomp?
			"lampbeamproxy.cpp"
			"lamphaloproxy.cpp"
			"mathproxy.cpp"
			"matrixproxy.cpp"
			"mat_stub.cpp"
			"menu.cpp"
			"message.cpp"
			"movehelper_client.cpp"
			"panelmetaclassmgr.cpp"
			"parsemsg.cpp"
			"particlemgr.cpp"
			"particles_ez.cpp"
			"particles_simple.cpp"
			"particle_collision.cpp"
			"particle_proxies.cpp"
			"particle_simple3d.cpp"
			"physics.cpp"
			"physics_main_client.cpp"
			"prediction.cpp"
			"proxyentity.cpp"
			"ProxyHealth.cpp"
			"proxyplayer.cpp"
			"proxypupil.cpp"
			"ragdoll.cpp"
			"recvproxy.cpp"
			"rendertexture.cpp" # Noprecomp?
			"simple_keys.cpp"
			"splinepatch.cpp"
			"spritemodel.cpp"
			"texturescrollmaterialproxy.cpp"
			"text_message.cpp"
			"timematerialproxy.cpp"
			"toggletextureproxy.cpp"
			"train.cpp"
			"vgui_basepanel.cpp"
			"vgui_bitmapbutton.cpp"
			"vgui_bitmapimage.cpp"
			"vgui_BudgetBarGraphPanel.cpp"
			"vgui_BudgetHistoryPanel.cpp"
			"vgui_BudgetPanel.cpp"
			"vgui_centerstringpanel.cpp"
			"vgui_connectmessagepanel.cpp"
			"vgui_consolepanel.cpp"
			"vgui_debugoverlaypanel.cpp"
			"vgui_downloadsliderpanel.cpp"
			"vgui_fpspanel.cpp"
			"vgui_game_viewport.cpp"
			"vgui_grid.cpp"
			"vgui_int.cpp"
			"vgui_loadingdiscpanel.cpp"
			"vgui_measuretimepanel.cpp"
			"vgui_messagechars.cpp"
			"vgui_netgraphpanel.cpp"
			"vgui_scorepanel.cpp"
			"vgui_textmessagepanel.cpp"
			"vgui_VProfGraphPanel.cpp"
			"vgui_vprofpanel.cpp"
			"view.cpp"
			"ViewConeImage.cpp"
			"view_beams.cpp"
			"view_effects.cpp"
			"view_scene.cpp"
			"warp_overlay.cpp"
			"weapons_resource.cpp"
			"weapon_selection.cpp"
			"WorldDimsProxy.cpp"
		#}
	)

	SRC_GRP(
		SUBGROUP "Precompiled Header"
		SOURCES
		#{
			"stdafx.cpp" # Create precomp: cbase.h
		#}
	)

	SRC_GRP(
		SUBGROUP "Temporary Entityes"
		SOURCES
		#{
			"c_basetempentity.cpp"
			"c_effects.cpp"
			"c_impact_effects.cpp"
			"c_movie_explosion.cpp"
			"c_particle_fire.cpp"
			"c_particle_smokegrenade.cpp"
			"c_smoke_trail.cpp"
			"c_smokestack.cpp"
			"c_splash.cpp"
			"c_steamjet.cpp"
			"c_te.cpp"
			"c_te_armorricochet.cpp"
			"c_te_basebeam.cpp"
			"c_te_beamentpoint.cpp"
			"c_te_beaments.cpp"
			"c_te_beamlaser.cpp"
			"c_te_beampoints.cpp"
			"c_te_beamring.cpp"
			"c_te_beamringpoint.cpp"
			"c_te_beamspline.cpp"
			"c_te_bloodsprite.cpp"
			"c_te_bloodstream.cpp"
			"c_te_breakmodel.cpp"
			"c_te_bspdecal.cpp"
			"c_te_bubbles.cpp"
			"c_te_bubbletrail.cpp"
			"c_te_decal.cpp"
			"c_te_dynamiclight.cpp"
			"c_te_effect_dispatch.cpp"
			"c_te_energysplash.cpp"
			"c_te_explosion.cpp"
			"c_te_fizz.cpp"
			"c_te_fogripple.cpp"
			"c_te_footprint.cpp"
			"c_te_glassshatter.cpp"
			"c_te_glowsprite.cpp"
			"c_te_impact.cpp"
			"c_te_killplayerattachments.cpp"
			"c_te_largefunnel.cpp"
			"c_te_legacytempents.cpp"
			"c_te_muzzleflash.cpp"
			"c_te_particlesystem.cpp"
			"c_te_playerdecal.cpp"
			"c_te_showline.cpp"
			"c_te_smoke.cpp"
			"c_te_sparks.cpp"
			"c_te_sprite.cpp"
			"c_te_spritespray.cpp"
			"c_te_textmessage.cpp"
			"c_te_worlddecal.cpp"
			"c_testtraceline.cpp"
			"c_tracer.cpp"
			"fx.cpp"
			"fx_discreetline.cpp"
			"fx_envelope.cpp"
			"fx_line.cpp"
			"fx_sparks.cpp"
			"particlesphererenderer.cpp"
			"smoke_fog_overlay.cpp"
		#}
	)
END_SRC( CLIENT_BASE_SOURCE_FILES "Source Files" )

set( CLIENT_BASE_HEADER_FILES )
BEGIN_SRC( CLIENT_BASE_HEADER_FILES "Header Files" )
	SRC_GRP(
		SOURCES
		#{
			"${SRCDIR}/common/con_nprint.h"
			"${SRCDIR}/engine/cl_ents_parse.h"

			"${SRCDIR}/game_shared/activitylist.h"
			"${SRCDIR}/game_shared/ai_activity.h"
			"${SRCDIR}/game_shared/ammodef.h"
			"${SRCDIR}/game_shared/animation.h"
			"${SRCDIR}/game_shared/baseentity_shared.h"
			"${SRCDIR}/game_shared/basegrenade_shared.h"
			"${SRCDIR}/game_shared/baseparticleentity.h"
			"${SRCDIR}/game_shared/baseplayer_shared.h"
			"${SRCDIR}/game_shared/baseviewmodel_shared.h"
			"${SRCDIR}/game_shared/beam_flags.h"
			"${SRCDIR}/game_shared/beam_shared.h"
			"${SRCDIR}/game_shared/bone_setup.h"
			"${SRCDIR}/game_shared/decals.h"
			"${SRCDIR}/game_shared/effect_dispatch_data.h"
			"${SRCDIR}/game_shared/ehandle.h"
			"${SRCDIR}/game_shared/entitylist_base.h"
			"${SRCDIR}/game_shared/env_wind_shared.h"
			"${SRCDIR}/game_shared/func_dust_shared.h"
			"${SRCDIR}/game_shared/gamemovement.h"
			"${SRCDIR}/game_shared/gamerules.h"
			"${SRCDIR}/game_shared/gamestringpool.h"
			"${SRCDIR}/game_shared/gamevars_shared.h"
			"${SRCDIR}/game_shared/hl_movedata.h"
			"${SRCDIR}/game_shared/IEffects.h"
			"${SRCDIR}/game_shared/igamesystem.h"
			"${SRCDIR}/game_shared/imovehelper.h"
			"${SRCDIR}/game_shared/interval.h"
			"${SRCDIR}/game_shared/in_buttons.h"
			"${SRCDIR}/game_shared/ipredictionsystem.h"
			"${SRCDIR}/game_shared/itempents.h"
			"${SRCDIR}/game_shared/IVehicle.h"
			"${SRCDIR}/game_shared/mapdata_shared.h"
			"${SRCDIR}/game_shared/movevars_shared.h"
			"${SRCDIR}/game_shared/multiplay_gamerules.h"
			"${SRCDIR}/game_shared/npcevent.h"
			"${SRCDIR}/game_shared/physics_saverestore.h"
			"${SRCDIR}/game_shared/physics_shared.h"
			"${SRCDIR}/game_shared/playernet_vars.h"
			"${SRCDIR}/game_shared/precache_register.h"
			"${SRCDIR}/game_shared/predictableid.h"
			"${SRCDIR}/game_shared/predictable_entity.h"
			"${SRCDIR}/game_shared/predictioncopy.h"
			"${SRCDIR}/game_shared/ragdoll_shared.h"
			"${SRCDIR}/game_shared/rope_helpers.h"
			"${SRCDIR}/game_shared/saverestore.h"
			"${SRCDIR}/game_shared/saverestore_bitstring.h"
			"${SRCDIR}/game_shared/saverestore_utlsymbol.h"
			"${SRCDIR}/game_shared/saverestore_utlvector.h"
			"${SRCDIR}/game_shared/scriptevent.h"
			"${SRCDIR}/game_shared/serial_entity.h"
			"${SRCDIR}/game_shared/shareddefs.h"
			"${SRCDIR}/game_shared/sharedInterface.h"
			"${SRCDIR}/game_shared/shared_classnames.h"
			"${SRCDIR}/game_shared/sheetsimulator.h"
			"${SRCDIR}/game_shared/singleplay_gamerules.h"
			"${SRCDIR}/game_shared/solidsetdefaults.h"
			"${SRCDIR}/game_shared/SoundEmitterSystemBase.h"
			"${SRCDIR}/game_shared/soundenvelope.h"
			"${SRCDIR}/game_shared/sprite.h"
			"${SRCDIR}/game_shared/SpriteTrail.h"
			"${SRCDIR}/game_shared/takedamageinfo.h"
			"${SRCDIR}/game_shared/tempentity.h"
			"${SRCDIR}/game_shared/terrainmodmgr_shared.h"
			"${SRCDIR}/game_shared/tf2/weapon_objectselection.h"
			"${SRCDIR}/game_shared/touchlink.h"
			"${SRCDIR}/game_shared/usermessages.h"
			"${SRCDIR}/game_shared/util_shared.h"
			"${SRCDIR}/game_shared/vgui_defaultinputsignal.h"
			"${SRCDIR}/game_shared/voice_banmgr.h"
			"${SRCDIR}/game_shared/voice_common.h"
			"${SRCDIR}/game_shared/voice_gamemgr.h"
			"${SRCDIR}/game_shared/voice_status.h"
			"${SRCDIR}/game_shared/vphysics_sound.h"
			"${SRCDIR}/game_shared/weapon_parse.h"

			"${SRCDIR}/public/appframework/IAppSystem.h"
			"${SRCDIR}/public/basehandle.h"
			"${SRCDIR}/public/basetypes.h"
			"${SRCDIR}/public/bitbuf.h"
			"${SRCDIR}/public/bitvec.h"
			"${SRCDIR}/public/bspfile.h"
			"${SRCDIR}/public/bspflags.h"
			"${SRCDIR}/public/bsptreedata.h"
			"${SRCDIR}/public/bumpvects.h"
			"${SRCDIR}/public/cache_user.h"
			"${SRCDIR}/public/cdll_int.h"
			"${SRCDIR}/public/characterset.h"
			"${SRCDIR}/public/checksum_crc.h"
			"${SRCDIR}/public/clientstats.h"
			"${SRCDIR}/public/client_class.h"
			"${SRCDIR}/public/client_command.h"
			"${SRCDIR}/public/client_textmessage.h"
			"${SRCDIR}/public/cmodel.h"
			"${SRCDIR}/public/collisionutils.h"
			"${SRCDIR}/public/Color.h"
			"${SRCDIR}/public/commonmacros.h"
			"${SRCDIR}/public/const.h"
			"${SRCDIR}/public/convar.h"
			"${SRCDIR}/public/coordsize.h"
			"${SRCDIR}/public/crtmemdebug.h"
			"${SRCDIR}/public/customentity.h"
			"${SRCDIR}/public/datamap.h"
			"${SRCDIR}/public/dlight.h"
			"${SRCDIR}/public/dt_common.h"
			"${SRCDIR}/public/dt_recv.h"
			"${SRCDIR}/public/dt_send.h"
			"${SRCDIR}/public/edict.h"
			"${SRCDIR}/public/engine/IClientLeafSystem.h"
			"${SRCDIR}/public/engine/icollideable.h"
			"${SRCDIR}/public/engine/IEngineSound.h"
			"${SRCDIR}/public/engine/IEngineTrace.h"
			"${SRCDIR}/public/engine/ishadowmgr.h"
			"${SRCDIR}/public/engine/IStaticPropMgr.h"
			"${SRCDIR}/public/engine/ivdebugoverlay.h"
			"${SRCDIR}/public/engine/ivmodelinfo.h"
			"${SRCDIR}/public/engine/ivmodelrender.h"
			"${SRCDIR}/public/filesystem.h"
			"${SRCDIR}/public/filesystem_helpers.h"
			"${SRCDIR}/public/fmtstr.h"
			"${SRCDIR}/public/gamebspfile.h"
			"${SRCDIR}/public/gametrace.h"
			"${SRCDIR}/public/globalvars_base.h"
			"${SRCDIR}/public/icliententity.h"
			"${SRCDIR}/public/icliententitylist.h"
			"${SRCDIR}/public/iclientnetworkable.h"
			"${SRCDIR}/public/iclientrenderable.h"
			"${SRCDIR}/public/iclientthinkable.h"
			"${SRCDIR}/public/iclientunknown.h"
			"${SRCDIR}/public/icvar.h"
			"${SRCDIR}/public/iefx.h"
			"${SRCDIR}/public/ienginevgui.h"
			"${SRCDIR}/public/igamemovement.h"
			"${SRCDIR}/public/IGameUIFuncs.h"
			"${SRCDIR}/public/ihandleentity.h"
			"${SRCDIR}/public/imageloader.h"
			"${SRCDIR}/public/inetgraph.h"
			"${SRCDIR}/public/inetworkstringtableclient.h"
			"${SRCDIR}/public/interface.h"
			"${SRCDIR}/public/iprediction.h"
			"${SRCDIR}/public/irecipientfilter.h"
			"${SRCDIR}/public/isaverestore.h"
			"${SRCDIR}/public/iserverentity.h"
			"${SRCDIR}/public/iservernetworkable.h"
			"${SRCDIR}/public/ispatialpartition.h"
			"${SRCDIR}/public/istudiorender.h"
			"${SRCDIR}/public/ivguicenterprint.h"
			"${SRCDIR}/public/ivrenderview.h"
			"${SRCDIR}/public/kbutton.h"
			"${SRCDIR}/public/keydefs.h"
			"${SRCDIR}/public/keyvalues.h"
			"${SRCDIR}/public/materialsystem/imaterial.h"
			"${SRCDIR}/public/materialsystem/imaterialproxy.h"
			"${SRCDIR}/public/materialsystem/imaterialsystem.h"
			"${SRCDIR}/public/materialsystem/imaterialsystemhardwareconfig.h"
			"${SRCDIR}/public/materialsystem/imaterialvar.h"
			"${SRCDIR}/public/materialsystem/imesh.h"
			"${SRCDIR}/public/materialsystem/itexture.h"
			"${SRCDIR}/public/mathlib.h"
			"${SRCDIR}/public/measure_section.h"
			"${SRCDIR}/public/mempool.h"
			"${SRCDIR}/public/mem_fgets.h"
			"${SRCDIR}/public/model_types.h"
			"${SRCDIR}/public/mouthinfo.h"
			"${SRCDIR}/public/networkstringtabledefs.h"
			"${SRCDIR}/public/networkvar.h"
			"${SRCDIR}/public/overlaytext.h"
			"${SRCDIR}/public/physdll.h"
			"${SRCDIR}/public/pixelwriter.h"
			"${SRCDIR}/public/plane.h"
			"${SRCDIR}/public/PlayerState.h"
			"${SRCDIR}/public/processor_detect.h"
			"${SRCDIR}/public/protected_things.h"
			"${SRCDIR}/public/rope_physics.h"
			"${SRCDIR}/public/rope_shared.h"
			"${SRCDIR}/public/r_efx.h"
			"${SRCDIR}/public/s3_intrf.h"
			"${SRCDIR}/public/saverestoretypes.h"
			"${SRCDIR}/public/sentence.h"
			"${SRCDIR}/public/server_class.h"
			"${SRCDIR}/public/shake.h"
			"${SRCDIR}/public/shattersurfacetypes.h"
			"${SRCDIR}/public/simple_physics.h"
			"${SRCDIR}/public/smartptr.h"
			"${SRCDIR}/public/soundflags.h"
			"${SRCDIR}/public/soundinfo.h"
			"${SRCDIR}/public/stringpool.h"
			"${SRCDIR}/public/stringregistry.h"
			"${SRCDIR}/public/string_t.h"
			"${SRCDIR}/public/studio.h"
			"${SRCDIR}/public/surfinfo.h"
			"${SRCDIR}/public/terrainmod.h"
			"${SRCDIR}/public/tgaloader.h"
			"${SRCDIR}/public/tier0/dbg.h"
			"${SRCDIR}/public/tier0/fasttimer.h"
			"${SRCDIR}/public/tier0/mem.h"
			"${SRCDIR}/public/tier0/memalloc.h"
			"${SRCDIR}/public/tier0/memdbgoff.h"
			"${SRCDIR}/public/tier0/memdbgon.h"
			"${SRCDIR}/public/tier0/platform.h"
			"${SRCDIR}/public/tier0/vprof.h"
			"${SRCDIR}/public/touchlist.h"
			"${SRCDIR}/public/usercmd.h"
			"${SRCDIR}/public/utlbidirectionalset.h"
			"${SRCDIR}/public/utlbuffer.h"
			"${SRCDIR}/public/utldict.h"
			"${SRCDIR}/public/utlfixedlinkedlist.h"
			"${SRCDIR}/public/utlfixedmemory.h"
			"${SRCDIR}/public/utllinkedlist.h"
			"${SRCDIR}/public/utlmap.h"
			"${SRCDIR}/public/utlmemory.h"
			"${SRCDIR}/public/utlmultilist.h"
			"${SRCDIR}/public/utlpriorityqueue.h"
			"${SRCDIR}/public/utlrbtree.h"
			"${SRCDIR}/public/utlsymbol.h"
			"${SRCDIR}/public/utlvector.h"
			"${SRCDIR}/public/vallocator.h"
			"${SRCDIR}/public/vcollide.h"
			"${SRCDIR}/public/vcollide_parse.h"
			"${SRCDIR}/public/vector.h"
			"${SRCDIR}/public/vector2d.h"
			"${SRCDIR}/public/vector4d.h"
			"${SRCDIR}/public/VGuiMatSurface/IMatSystemSurface.h"
			"${SRCDIR}/public/vgui/Cursor.h"
			"${SRCDIR}/public/vgui/Dar.h"
			"${SRCDIR}/public/vgui/IClientPanel.h"
			"${SRCDIR}/public/vgui/IHTML.h"
			"${SRCDIR}/public/vgui/IImage.h"
			"${SRCDIR}/public/vgui/IInput.h"
			"${SRCDIR}/public/vgui/IInputInternal.h"
			"${SRCDIR}/public/vgui/ILocalize.h"
			"${SRCDIR}/public/vgui/IPanel.h"
			"${SRCDIR}/public/vgui/IScheme.h"
			"${SRCDIR}/public/vgui/ISurface.h"
			"${SRCDIR}/public/vgui/ISystem.h"
			"${SRCDIR}/public/vgui/IVGui.h"
			"${SRCDIR}/public/vgui/KeyCode.h"
			"${SRCDIR}/public/vgui/MessageMap.h"
			"${SRCDIR}/public/vgui/MouseCode.h"
			"${SRCDIR}/public/vgui/VGUI.h"
			"${SRCDIR}/public/vgui_controls/AnimationController.h"
			"${SRCDIR}/public/vgui_controls/Button.h"
			"${SRCDIR}/public/vgui_controls/Controls.h"
			"${SRCDIR}/public/vgui_controls/EditablePanel.h"
			"${SRCDIR}/public/vgui_controls/FocusNavGroup.h"
			"${SRCDIR}/public/vgui_controls/Image.h"
			"${SRCDIR}/public/vgui_controls/Label.h"
			"${SRCDIR}/public/vgui_controls/Panel.h"
			"${SRCDIR}/public/vgui_controls/PanelAnimationVar.h"
			"${SRCDIR}/public/vgui_controls/PanelListPanel.h"
			"${SRCDIR}/public/vgui_controls/PHandle.h"
			"${SRCDIR}/public/vgui_controls/RichText.h"
			"${SRCDIR}/public/vgui_controls/ScrollBar.h"
			"${SRCDIR}/public/vgui_controls/TextEntry.h"
			"${SRCDIR}/public/vgui_controls/TextImage.h"
			"${SRCDIR}/public/vgui_controls/TreeView.h"
			"${SRCDIR}/public/view_shared.h"
			"${SRCDIR}/public/vmatrix.h"
			"${SRCDIR}/public/vphysics/constraints.h"
			"${SRCDIR}/public/vphysics_interface.h"
			"${SRCDIR}/public/vplane.h"
			"${SRCDIR}/public/vstdlib/icommandline.h"
			"${SRCDIR}/public/vstdlib/random.h"
			"${SRCDIR}/public/vstdlib/strtools.h"
			"${SRCDIR}/public/vstdlib/vstdlib.h"
			"${SRCDIR}/public/vtf/vtf.h"
			"${SRCDIR}/public/worldsize.h"

			"animationlayer.h"
			"baseanimatedtextureproxy.h"
			"BaseModViewport.h" # !TF2 && !HL1 && !HL2
			"beamdraw.h"
			"cbase.h"
			"cdll_client_int.h"
			"cdll_convar.h"
			"cdll_util.h"
			"clienteffectprecachesystem.h"
			"cliententitylist.h"
			"clientleafsystem.h"
			"clientmode.h"
			"clientmode_shared.h"
			"clientsideeffects.h"
			"client_thinklist.h"
			"cl_animevent.h"
			"c_ai_basenpc.h"
			"c_baseanimating.h"
			"c_baseanimatingoverlay.h"
			"c_basecombatcharacter.h"
			"c_basecombatweapon.h"
			"c_basedoor.h"
			"c_baseentity.h"
			"c_baseflex.h"
			"c_basenetworkable.h"
			"c_baseplayer.h"
			"c_baseviewmodel.h"
			"c_breakableprop.h"
			"c_clientstats.h"
			"c_func_dust.h"
			"c_gib.h"
			"c_impact_effects.h"
			"c_physbox.h"
			"c_physicsprop.h"
			"c_playerlocaldata.h"
			"c_playerresource.h"
			"c_prop_vehicle.h"
			"c_recipientfilter.h"
			"c_rope.h"
			"c_smoke_trail.h"
			"c_soundscape.h"
			"c_splash.h"
			"c_sprite.h"
			"c_sun.h"
			"c_team.h"
			"c_terrainmodmgr.h"
			"c_te_basebeam.h"
			"c_te_effect_dispatch.h"
			"c_te_legacytempents.h"
			"c_te_particlesystem.h"
			"c_tracer.h"
			"c_user_message_register.h"
			"c_vguiscreen.h"
			"c_weapon__stubs.h"
			"c_world.h"
			"detailobjectsystem.h"
			"enginesprite.h"
			"fontabc.h"
			"functionproxy.h"
			"fx.h"
			"fx_blood.h"
			"fx_discreetline.h"
			"fx_envelope.h"
			"fx_explosion.h"
			"fx_fleck.h"
			"fx_impact.h"
			"fx_line.h"
			"fx_quad.h"
			"fx_sparks.h"
			"fx_staticline.h"
			"glow_overlay.h"
			"history_resource.h"
			"${SRCDIR}/game_shared/hl2_player_shared.h"
			"hud.h"
			"hudelement.h"
			"hudtexturehandle.h"
			"hud_chat.h"
			"hud_closecaption.h"
			"hud_crosshair.h"
			"hud_element_helper.h"
			"hud_macros.h"
			"hud_numericdisplay.h" # !TF2 && !HL1
			"hud_pdump.h"
			"hud_vehicle.h"
			"iclassmap.h"
			"icliententityinternal.h"
			"iclientmode.h"
			"iclientshadowmgr.h"
			"iclientvehicle.h"
			"iconnectmsg.h"
			"iconsole.h"
			"idebugoverlaypanel.h"
			"idownloadslider.h"
			"ifpspanel.h"
			"iinput.h"
			"iloadingdisc.h"
			"imessagechars.h"
			"inetgraphpanel.h"
			"initializer.h"
			"input.h"
			"interpolatedvar.h"
			"in_main.h"
			"iprofiling.h"
			"itextmessage.h"
			"ivieweffects.h"
			"iviewrender.h"
			"iviewrender_beams.h"
			"ivmodemanager.h"
			"mat_stub.h"
			"menu.h"
			"movehelper_client.h"
			"networkstringtable_clientdll.h"
			"panelmetaclassmgr.h"
			"parsemsg.h"
			"particledraw.h"
			"particlemgr.h"
			"particlesphererenderer.h"
			"particles_ez.h"
			"particles_simple.h"
			"particle_collision.h"
			"particle_prototype.h"
			"particle_simple3d.h"
			"particle_util.h"
			"physics.h"
			"prediction.h"
			"prediction_private.h"
			"proxyentity.h"
			"ragdoll.h"
			"ragdollexplosionenumerator.h"
			"recvproxy.h"
			"rendertexture.h"
			"simple_keys.h"
			"smoke_fog_overlay.h"
			"splinepatch.h"
			"TeamBitmapImage.h"
			"tempent.h"
			"text_message.h"
			"toggletextureproxy.h"
			"vguicenterprint.h"
			"vgui_basepanel.h"
			"vgui_bitmapbutton.h"
			"vgui_bitmapimage.h"
			"vgui_bitmappanel.h"
			"vgui_BudgetBarGraphPanel.h"
			"vgui_BudgetHistoryPanel.h"
			"vgui_BudgetPanel.h"
			"vgui_entityimagepanel.h"
			"vgui_entitypanel.h"
			"vgui_grid.h"
			"tf2_hud/vgui_healthbar.h"
			"vgui_helpers.h"
			"vgui_imagehealthpanel.h"
			"vgui_int.h"
			"vgui_scorepanel.h"
			"vgui_vprofpanel.h"
			"view.h"
			"ViewConeImage.h"
			"viewrender.h"
			"view_scene.h"
			"weapons_resource.h"
			"weapon_selection.h"
		#}
	)
END_SRC( CLIENT_BASE_HEADER_FILES "Header Files" )

function( target_use_client_base target EXCLUDE_SOURCES )

	set( USED_SOURCES ${CLIENT_BASE_SOURCE_FILES} ${CLIENT_BASE_HEADER_FILES} )

	if( ${EXCLUDE_SOURCES} )
		list( REMOVE_ITEM USED_SOURCES ${${EXCLUDE_SOURCES}} )
	endif()

	set_property( TARGET ${target} PROPERTY FOLDER "Game" )

	set_target_properties(
		${target} PROPERTIES

		LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/cl_dll/${target}"
		RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/cl_dll/${target}"
		ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/cl_dll/${target}"
	)

	target_sources( ${target} PRIVATE ${USED_SOURCES} )

	target_include_directories(
		${target} PRIVATE

		"${SRCDIR}/cl_dll"
		"${SRCDIR}/game_shared"
	)

	target_compile_definitions(
		${target} PRIVATE

		"$<$<CONFIG:Debug>:fopen=dont_use_fopen>"
		NO_STRING_T
		CLIENT_DLL
		VECTOR
		strncpy=use_Q_strncpy_instead
		_snprintf=use_Q_snprintf_instead
		PROTECTED_THINGS_ENABLE

		"$<${IS_LINUX}:IMAGE_LOADER_NO_DXTC>"
	)

	target_precompile_headers(
		${target}
		PRIVATE "cbase.h"
	)

	target_link_libraries(
		${target} PRIVATE

		"$<${IS_WINDOWS}:winmm>"

		"${LIBCOMMON}/s3tc.lib"
		game_controls
		vgui_controls
		vstdlib
	)

endfunction()
