//=========== Copyright © 1996-2003, Valve LLC, All rights reserved. ===========
//
// Purpose: BarrysMod Tool Buttons Panel Layout - Identical to Garry's Mod
//
//=============================================================================

"Resource/UI/menu_toolbuttons.res"
{
	"ToolButtonsPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"ToolButtonsPanel"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"238"
		"tall"				"480"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"bgcolor_override"	"50 50 50 200"
	}

	"ToolButton1"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton1"
		"xpos"				"4"
		"ypos"				"4"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Gun"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_1"
		"default"			"0"
	}

	"ToolButton2"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton2"
		"xpos"				"40"
		"ypos"				"4"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Phys"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_2"
		"default"			"0"
	}

	"ToolButton3"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton3"
		"xpos"				"76"
		"ypos"				"4"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Cam"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_3"
		"default"			"0"
	}

	"ToolButton4"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton4"
		"xpos"				"112"
		"ypos"				"4"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"NPC"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_4"
		"default"			"0"
	}

	"ToolButton5"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton5"
		"xpos"				"148"
		"ypos"				"4"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Bot"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_5"
		"default"			"0"
	}

	"ToolButton6"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton6"
		"xpos"				"184"
		"ypos"				"4"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Mat"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_6"
		"default"			"0"
	}

	"ToolButton7"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton7"
		"xpos"				"4"
		"ypos"				"40"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Col"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_7"
		"default"			"0"
	}

	"ToolButton8"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton8"
		"xpos"				"40"
		"ypos"				"40"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Paint"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_8"
		"default"			"0"
	}

	"ToolButton9"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton9"
		"xpos"				"76"
		"ypos"				"40"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Infl"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_9"
		"default"			"0"
	}

	"ToolButton10"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton10"
		"xpos"				"112"
		"ypos"				"40"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Dup"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_10"
		"default"			"0"
	}

	"ToolButton11"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton11"
		"xpos"				"148"
		"ypos"				"40"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Cons"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_11"
		"default"			"0"
	}

	"ToolButton12"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton12"
		"xpos"				"184"
		"ypos"				"40"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Axis"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_12"
		"default"			"0"
	}

	"ToolButton13"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton13"
		"xpos"				"4"
		"ypos"				"76"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Ball"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_13"
		"default"			"0"
	}

	"ToolButton14"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton14"
		"xpos"				"40"
		"ypos"				"76"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Rope"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_14"
		"default"			"0"
	}

	"ToolButton15"
	{
		"ControlName"		"Button"
		"fieldName"			"ToolButton15"
		"xpos"				"76"
		"ypos"				"76"
		"wide"				"32"
		"tall"				"32"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Pull"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"tool_15"
		"default"			"0"
	}

	// Props/Entities Panel
	"PropsPanel"
	{
		"ControlName"		"Panel"
		"fieldName"			"PropsPanel"
		"xpos"				"0"
		"ypos"				"120"
		"wide"				"238"
		"tall"				"350"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"bgcolor_override"	"40 40 40 150"
	}

	"PropsLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"PropsLabel"
		"xpos"				"5"
		"ypos"				"125"
		"wide"				"100"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"Props & Entities"
		"textAlignment"		"west"
		"dulltext"			"0"
		"brighttext"		"0"
		"font"				"DefaultBold"
		"fgcolor_override"	"255 255 255 255"
	}

	// Search box
	"SearchBox"
	{
		"ControlName"		"TextEntry"
		"fieldName"			"SearchBox"
		"xpos"				"5"
		"ypos"				"150"
		"wide"				"228"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"			"1"
		"maxchars"			"80"
		"NumericInputOnly"	"0"
		"unicode"			"0"
		"wrap"				"0"
		"fgcolor_override"	"255 255 255 255"
		"bgcolor_override"	"0 0 0 100"
		"placeholderText"	"Search for props..."
	}

	// Categories list
	"CategoriesList"
	{
		"ControlName"		"SectionedListPanel"
		"fieldName"			"CategoriesList"
		"xpos"				"5"
		"ypos"				"175"
		"wide"				"110"
		"tall"				"290"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"linespacing"		"16"
		"fgcolor_override"	"255 255 255 255"
		"bgcolor_override"	"0 0 0 100"
	}

	// Props list
	"PropsList"
	{
		"ControlName"		"SectionedListPanel"
		"fieldName"			"PropsList"
		"xpos"				"120"
		"ypos"				"175"
		"wide"				"113"
		"tall"				"290"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"linespacing"		"16"
		"fgcolor_override"	"255 255 255 255"
		"bgcolor_override"	"0 0 0 100"
	}
}