include_guard( GLOBAL )

set( SERVER_BASE_SOURCE_FILES )
BEGIN_SRC( SERVER_BASE_SOURCE_FILES "Source Files" )
	SRC_GRP(
		SOURCES
		#{
			"${SRCDIR}/common/keyframe/keyframe.cpp" # Noprecomp?

			"${SRCDIR}/game_shared/activitylist.cpp"
			"${SRCDIR}/game_shared/ammodef.cpp"
			"${SRCDIR}/game_shared/animation.cpp"
			"${SRCDIR}/game_shared/basecombatcharacter_shared.cpp"
			"${SRCDIR}/game_shared/basecombatweapon_shared.cpp"
			"${SRCDIR}/game_shared/baseentity_shared.cpp"
			"${SRCDIR}/game_shared/basegrenade_shared.cpp"
			"${SRCDIR}/game_shared/baseparticleentity.cpp"
			"${SRCDIR}/game_shared/baseplayer_shared.cpp"
			"${SRCDIR}/game_shared/baseviewmodel_shared.cpp"
			"${SRCDIR}/game_shared/beam_shared.cpp"
			"${SRCDIR}/game_shared/bone_setup.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/choreoactor.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/choreochannel.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/choreoevent.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/choreoscene.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/collisionproperty.cpp"
			"${SRCDIR}/game_shared/decals.cpp"
			"${SRCDIR}/game_shared/effect_dispatch_data.cpp"
			"${SRCDIR}/game_shared/ehandle.cpp"
			"${SRCDIR}/game_shared/entitylist_base.cpp"
			"${SRCDIR}/game_shared/env_wind_shared.cpp"
			"${SRCDIR}/game_shared/gamemovement.cpp"
			"${SRCDIR}/game_shared/gamerules.cpp"
			"${SRCDIR}/game_shared/gamestringpool.cpp"
			"${SRCDIR}/game_shared/gamevars_shared.cpp"
			"${SRCDIR}/game_shared/igamesystem.cpp"
			"${SRCDIR}/game_shared/interval.cpp"
			"${SRCDIR}/game_shared/movevars_shared.cpp"
			"${SRCDIR}/game_shared/multiplay_gamerules.cpp"
			"${SRCDIR}/game_shared/physics_main_shared.cpp"
			"${SRCDIR}/game_shared/physics_saverestore.cpp"
			"${SRCDIR}/game_shared/physics_shared.cpp"
			"${SRCDIR}/game_shared/precache_register.cpp"
			"${SRCDIR}/game_shared/predictableid.cpp"
			"${SRCDIR}/game_shared/ragdoll_shared.cpp"
			"${SRCDIR}/game_shared/rope_helpers.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/saverestore.cpp"
			"${SRCDIR}/game_shared/sheetsimulator.cpp" # Noprecomp?
			"${SRCDIR}/game_shared/singleplay_gamerules.cpp"
			"${SRCDIR}/game_shared/SoundEmitterSystem.cpp"
			"${SRCDIR}/game_shared/SoundEmitterSystemBase.cpp"
			"${SRCDIR}/game_shared/soundenvelope.cpp"
			"${SRCDIR}/game_shared/sprite.cpp"
			"${SRCDIR}/game_shared/takedamageinfo.cpp"
			"${SRCDIR}/game_shared/teamplay_gamerules.cpp"
			"${SRCDIR}/game_shared/test_ehandle.cpp"
			"${SRCDIR}/game_shared/usermessages.cpp"
			"${SRCDIR}/game_shared/util_shared.cpp"
			"${SRCDIR}/game_shared/voice_gamemgr.cpp"
			"${SRCDIR}/game_shared/weapon_parse.cpp"
			"${SRCDIR}/game_shared/weapon_parse_default.cpp" # !CSTRIKE

			"${SRCDIR}/public/bitbuf.cpp" # Noprecomp?
			"${SRCDIR}/public/characterset.cpp" # Noprecomp?
			"${SRCDIR}/public/checksum_crc.cpp" # Noprecomp?
			"${SRCDIR}/public/collisionutils.cpp" # Noprecomp?
			"${SRCDIR}/public/convar.cpp" # Noprecomp?
			"${SRCDIR}/public/dt_send.cpp" # Noprecomp?
			"${SRCDIR}/public/editor_sendcommand.cpp" # Noprecomp?
			"${SRCDIR}/public/filesystem_helpers.cpp" # Noprecomp?
			"${SRCDIR}/public/interface.cpp" # Noprecomp?
			"${SRCDIR}/public/keyvalues.cpp" # Noprecomp?
			"${SRCDIR}/public/mathlib.cpp" # Noprecomp?
			"${SRCDIR}/public/measure_section.cpp" # Noprecomp?
			"${SRCDIR}/public/mempool.cpp" # Noprecomp?
			"${SRCDIR}/public/mem_fgets.cpp" # Noprecomp?
			"${SRCDIR}/public/networkvar.cpp" # Noprecomp?
			"${SRCDIR}/public/rope_physics.cpp" # Noprecomp?
			"${SRCDIR}/public/server_class.cpp" # Noprecomp?
			"${SRCDIR}/public/simple_physics.cpp" # Noprecomp?
			"${SRCDIR}/public/stringpool.cpp"
			"${SRCDIR}/public/stringregistry.cpp" # Noprecomp?
			#"${SRCDIR}/public/tier0/memoverride.cpp" # Noprecomp?
			"${SRCDIR}/public/UserCmd.cpp"
			"${SRCDIR}/public/utlbuffer.cpp" # Noprecomp?
			"${SRCDIR}/public/utlsymbol.cpp" # Noprecomp?
			"${SRCDIR}/public/vmatrix.cpp" # Noprecomp?

			"actanimating.cpp"
			"ai_activity.cpp"
			"ai_baseactor.cpp"
			"ai_basehumanoid.cpp"
			"ai_basehumanoid_movement.cpp"
			"ai_basenpc.cpp"
			"ai_basenpc_flyer.cpp"
			"ai_basenpc_flyer_new.cpp"
			"ai_basenpc_movement.cpp"
			"ai_basenpc_physicsflyer.cpp"
			"ai_basenpc_schedule.cpp"
			"ai_basenpc_squad.cpp"
			"ai_behavior.cpp"
			"ai_behavior_assault.cpp"
			"ai_behavior_follow.cpp"
			"ai_behavior_lead.cpp"
			"ai_behavior_standoff.cpp"
			"ai_concommands.cpp"
			"ai_condition.cpp"
			"AI_Criteria.cpp"
			"ai_default.cpp"
			"ai_dynamiclink.cpp"
			"ai_goalentity.cpp"
			"ai_hint.cpp"
			"ai_hull.cpp"
			"ai_initutils.cpp"
			"ai_link.cpp"
			"ai_localnavigator.cpp"
			"ai_memory.cpp"
			"ai_motor.cpp"
			"ai_moveprobe.cpp"
			"ai_moveshoot.cpp"
			"ai_movesolver.cpp"
			"ai_namespaces.cpp"
			"ai_navigator.cpp"
			"ai_nav_property.cpp"
			"ai_network.cpp"
			"ai_networkmanager.cpp"
			"ai_node.cpp"
			"ai_pathfinder.cpp"
			"ai_planesolver.cpp"
			"AI_ResponseSystem.cpp"
			"ai_route.cpp"
			"ai_saverestore.cpp"
			"ai_schedule.cpp"
			"ai_scriptconditions.cpp"
			"ai_senses.cpp"
			"ai_speech.cpp"
			"ai_squad.cpp"
			"ai_squadslot.cpp"
			"ai_tacticalservices.cpp"
			"ai_task.cpp"
			"ai_trackpather.cpp"
			"ai_utils.cpp"
			"ai_waypoint.cpp"
			"animating.cpp"
			"BaseAnimatingOverlay.cpp"
			"basecombatcharacter.cpp"
			"basecombatweapon.cpp"
			"baseentity.cpp"
			"baseflex.cpp"
			"basegrenade_concussion.cpp" # !CSTRIKE
			"basegrenade_contact.cpp" # !CSTRIKE
			"basegrenade_timed.cpp" # !CSTRIKE
			"basenetworkable.cpp"
			"baseviewmodel.cpp"
			"base_transmit_proxy.cpp"
			"bitstring.cpp"
			"bmodels.cpp"
			"buttons.cpp"
			"cbase.cpp"
			"client.cpp"
			"controlentities.cpp"
			"CRagdollMagnet.cpp"
			"cterrainmorph.cpp" # !TF2
			"damagemodifier.cpp"
			"doors.cpp"
			"dynamiclight.cpp"
			"effects.cpp"
			"EffectsServer.cpp"
			"EntityFlame.cpp"
			"entitylist.cpp"
			"EnvBeam.cpp"
			"EnvFade.cpp"
			"EnvLaser.cpp"
			"EnvMessage.cpp"
			"envmicrophone.cpp"
			"EnvShake.cpp"
			"EnvSpark.cpp"
			"env_entity_maker.cpp"
			"env_screenoverlay.cpp"
			"env_texturetoggle.cpp"
			"env_zoom.cpp"
			"eventlog.cpp"
			"explode.cpp"
			"filters.cpp"
			"fire.cpp"
			"fire_smoke.cpp"
			"fogcontroller.cpp"
			"fourwheelvehiclephysics.cpp"
			"func_areaportal.cpp"
			"func_areaportalbase.cpp"
			"func_areaportalwindow.cpp"
			"func_break.cpp"
			"func_breakablesurf.cpp"
			"func_dust.cpp"
			"func_lod.cpp"
			"func_movelinear.cpp"
			"func_occluder.cpp"
			"func_smokevolume.cpp"
			"game.cpp"
			"gameinterface.cpp"
			"gametrace_dll.cpp"
			"game_ui.cpp"
			"genericactor.cpp"
			"genericmonster.cpp"
			"gib.cpp"
			"globals.cpp"
			"globalstate.cpp"
			"grenadethrown.cpp" # !CSTRIKE
			"guntarget.cpp"
			"hierarchy.cpp"
			"h_ai.cpp"
			"h_cycler.cpp" # !CSTRIKE
			"h_export.cpp" # Noprecomp?
			"init_factory.cpp" # Noprecomp?
			"intermission.cpp"
			"item_world.cpp"
			"lightglow.cpp"
			"lights.cpp"
			"logicauto.cpp"
			"logicentities.cpp"
			"logicrelay.cpp"
			"logic_navigation.cpp"
			"mapentities.cpp" # Noprecomp?
			"maprules.cpp"
			"message_entity.cpp"
			"modelentities.cpp"
			"monstermaker.cpp" # !CSTRIKE && !HL1
			"movehelper_server.cpp"
			"movement.cpp"
			"ndebugoverlay.cpp"
			"netstatemgr.cpp"
			"npc_talker.cpp"
			"particle_light.cpp"
			"pathcorner.cpp"
			"physconstraint.cpp"
			"physgun.cpp" # !CSTRIKE && !TF2
			"physics.cpp"
			"physics_bone_follower.cpp"
			"physics_cannister.cpp"
			"physics_fx.cpp"
			"physics_impact_damage.cpp"
			"physics_main.cpp"
			"physics_prop_ragdoll.cpp"
			"physobj.cpp"
			"phys_controller.cpp"
			"plats.cpp"
			"player.cpp"
			"playerlocaldata.cpp"
			"player_command.cpp"
			"player_lagcompensation.cpp"
			"player_resource.cpp"
			"pointanglesensor.cpp"
			"PointAngularVelocitySensor.cpp"
			"pointhurt.cpp"
			"pointteleport.cpp"
			"point_playermoveconstraint.cpp"
			"point_template.cpp"
			"props.cpp"
			"recipientfilter.cpp"
			"rope.cpp"
			"saverestore_gamedll.cpp"
			"sceneentity.cpp"
			"scripted.cpp"
			"scriptedtarget.cpp"
			"sendproxy.cpp" # Noprecomp?
			"shadowcontrol.cpp"
			"simtimer.cpp"
			"skycamera.cpp"
			"sound.cpp"
			"soundent.cpp"
			"splash.cpp"
			"subs.cpp"
			"sun.cpp"
			"tanktrain.cpp"
			"te_effect_dispatch.cpp"
			"team.cpp"
			"team_spawnpoint.cpp"
			"TemplateEntities.cpp"
			"tempmonster.cpp"
			"terrainmodmgr.cpp"
			"testfunctions.cpp"
			"testtraceline.cpp"
			"test_proxytoggle.cpp"
			"test_stressentities.cpp"
			"textstatsmgr.cpp" # Noprecomp?
			"triggers.cpp"
			"util.cpp"
			"variant_t.cpp"
			"vguiscreen.cpp"
			"wcedit.cpp"
			"world.cpp"
		#}
	)

	SRC_GRP(
		SUBGROUP "Precompiled Header"
		SOURCES
		#{
			"stdafx.cpp" # Create precomp: cbase.h
		#}
	)

	SRC_GRP(
		SUBGROUP "temporary entities"
		SOURCES
		#{
			"hl2_dll/antlion_dust.cpp" # !CSTRIKE && !TF2
			"hl2_dll/antlion_dust.h"
			"hl2_dll/assassin_smoke.cpp" # !CSTRIKE && !TF2
			"hl2_dll/assassin_smoke.h" # !TF2
			"basetempentity.cpp"
			"cplane.cpp"
			"event_tempentity_tester.cpp"
			"movie_explosion.cpp"
			"particle_fire.cpp"
			"particle_smokegrenade.cpp"
			"plasma.cpp"
			"plasma.h"
			"hl2_dll/rotorwash.cpp" # !CSTRIKE && !TF2
			"hl2_dll/rotorwash.h" # !CSTRIKE && !TF2
			"smoke_trail.cpp" # !CSTRIKE
			"smoke_trail.h"
			"smokestack.cpp"
			"smokestack.h"
			"${SRCDIR}/game_shared/SpriteTrail.cpp"
			"steamjet.cpp"
			"steamjet.h"
			"te.cpp"
			"te.h"
			"te_armorricochet.cpp"
			"te_basebeam.cpp"
			"te_basebeam.h"
			"te_beamentpoint.cpp"
			"te_beaments.cpp"
			"te_beamlaser.cpp"
			"te_beampoints.cpp"
			"te_beamring.cpp"
			"te_beamringpoint.cpp"
			"te_beamspline.cpp"
			"te_bloodsprite.cpp"
			"te_bloodstream.cpp"
			"te_breakmodel.cpp"
			"te_bspdecal.cpp"
			"te_bubbles.cpp"
			"te_bubbletrail.cpp"
			"te_decal.cpp"
			"te_dynamiclight.cpp"
			"te_energysplash.cpp"
			"te_explosion.cpp"
			"te_fizz.cpp"
			"te_fogripple.cpp"
			"te_footprintdecal.cpp"
			"te_glassshatter.cpp"
			"te_glowsprite.cpp"
			"te_impact.cpp"
			"te_killplayerattachments.cpp"
			"te_largefunnel.cpp"
			"te_muzzleflash.cpp"
			"te_particlesystem.cpp"
			"te_particlesystem.h"
			"te_playerdecal.cpp"
			"te_showline.cpp"
			"te_smoke.cpp"
			"te_sparks.cpp"
			"te_sprite.cpp"
			"te_spritespray.cpp"
			"te_textmessage.cpp"
			"te_worlddecal.cpp"
		#}
	)
END_SRC( SERVER_BASE_SOURCE_FILES "Source Files" )

set( SERVER_BASE_HEADER_FILES )
BEGIN_SRC( SERVER_BASE_HEADER_FILES "Header Files" )
	SRC_GRP(
		SOURCES
		#{
			"${SRCDIR}/common/keyframe/keyframe.h"

			"${SRCDIR}/game_shared/activitylist.h"
			"${SRCDIR}/game_shared/ai_activity.h"
			"${SRCDIR}/game_shared/ammodef.h"
			"${SRCDIR}/game_shared/animation.h"
			"${SRCDIR}/game_shared/basecombatweapon_shared.h"
			"${SRCDIR}/game_shared/baseentity_shared.h"
			"${SRCDIR}/game_shared/basegrenade_shared.h"
			"${SRCDIR}/game_shared/baseparticleentity.h"
			"${SRCDIR}/game_shared/baseplayer_shared.h"
			"${SRCDIR}/game_shared/baseviewmodel_shared.h"
			"${SRCDIR}/game_shared/beam_flags.h"
			"${SRCDIR}/game_shared/beam_shared.h"
			"${SRCDIR}/game_shared/bone_setup.h"
			"${SRCDIR}/game_shared/choreoactor.h"
			"${SRCDIR}/game_shared/choreochannel.h"
			"${SRCDIR}/game_shared/choreoevent.h"
			"${SRCDIR}/game_shared/choreoscene.h"
			"${SRCDIR}/game_shared/collisionproperty.h"
			"${SRCDIR}/game_shared/decals.h"
			"${SRCDIR}/game_shared/effect_dispatch_data.h"
			"${SRCDIR}/game_shared/ehandle.h"
			"${SRCDIR}/game_shared/entitylist_base.h"
			"${SRCDIR}/game_shared/env_wind_shared.h"
			"${SRCDIR}/game_shared/expressionsample.h"
			"${SRCDIR}/game_shared/func_dust_shared.h"
			"${SRCDIR}/game_shared/gamemovement.h"
			"${SRCDIR}/game_shared/gamerules.h"
			"${SRCDIR}/game_shared/gamestringpool.h"
			"${SRCDIR}/game_shared/gamevars_shared.h"
			"${SRCDIR}/game_shared/hl2_player_shared.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/hl2_shareddefs.h" # !CSTRIKE && !TF2
			"${SRCDIR}/game_shared/hl_movedata.h" # !CSTRIKE && !TF2
			"${SRCDIR}/game_shared/ichoreoeventcallback.h"
			"${SRCDIR}/game_shared/IEffects.h"
			"${SRCDIR}/game_shared/igamesystem.h"
			"${SRCDIR}/game_shared/imovehelper.h"
			"${SRCDIR}/game_shared/interval.h"
			"${SRCDIR}/game_shared/in_buttons.h"
			"${SRCDIR}/game_shared/ipredictionsystem.h"
			"${SRCDIR}/game_shared/iscenetokenprocessor.h"
			"${SRCDIR}/game_shared/itempents.h"
			"${SRCDIR}/game_shared/IVehicle.h"
			"${SRCDIR}/game_shared/movevars_shared.h"
			"${SRCDIR}/game_shared/multiplay_gamerules.h"
			"${SRCDIR}/game_shared/npcevent.h"
			"${SRCDIR}/game_shared/physics_saverestore.h"
			"${SRCDIR}/game_shared/physics_shared.h"
			"${SRCDIR}/game_shared/playernet_vars.h"
			"${SRCDIR}/game_shared/precache_register.h"
			"${SRCDIR}/game_shared/predictableid.h"
			"${SRCDIR}/game_shared/predictable_entity.h"
			"${SRCDIR}/game_shared/predictioncopy.h"
			"${SRCDIR}/game_shared/ragdoll_shared.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/rope_helpers.h"
			"${SRCDIR}/game_shared/saverestore.h"
			"${SRCDIR}/game_shared/saverestore_bitstring.h"
			"${SRCDIR}/game_shared/saverestore_utlsymbol.h"
			"${SRCDIR}/game_shared/saverestore_utlvector.h"
			"${SRCDIR}/game_shared/scriptevent.h"
			"${SRCDIR}/game_shared/serial_entity.h"
			"${SRCDIR}/game_shared/shareddefs.h"
			"${SRCDIR}/game_shared/sharedInterface.h"
			"${SRCDIR}/game_shared/shared_classnames.h"
			"${SRCDIR}/game_shared/sheetsimulator.h"
			"${SRCDIR}/game_shared/singleplay_gamerules.h"
			"${SRCDIR}/game_shared/solidsetdefaults.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/SoundEmitterSystemBase.h"
			"${SRCDIR}/game_shared/soundenvelope.h"
			"${SRCDIR}/game_shared/sprite.h"
			"${SRCDIR}/game_shared/SpriteTrail.h"
			"${SRCDIR}/game_shared/takedamageinfo.h"
			"${SRCDIR}/game_shared/teamplay_gamerules.h"
			"${SRCDIR}/game_shared/tempentity.h"
			"${SRCDIR}/game_shared/terrainmodmgr_shared.h"
			"${SRCDIR}/game_shared/tf2/baseobject_shared.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/tf2/basetfvehicle.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/tf2/env_laserdesignation.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/tf2/ihasbuildpoints.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/tf2/tf_obj_base_manned_gun.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/tf2/tf_obj_manned_plasmagun_shared.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/tf2/vehicle_mortar_shared.h"
			"${SRCDIR}/game_shared/touchlink.h" # !CSTRIKE && !HL1
			"${SRCDIR}/game_shared/usermessages.h"
			"${SRCDIR}/game_shared/util_shared.h"
			"${SRCDIR}/game_shared/voice_common.h"
			"${SRCDIR}/game_shared/voice_gamemgr.h"
			"${SRCDIR}/game_shared/vphysics_sound.h"
			"${SRCDIR}/game_shared/weapon_parse.h"

			"${SRCDIR}/public/appframework/IAppSystem.h"
			"${SRCDIR}/public/basehandle.h"
			"${SRCDIR}/public/basetypes.h"
			"${SRCDIR}/public/bitbuf.h"
			"${SRCDIR}/public/bitvec.h"
			"${SRCDIR}/public/bspfile.h"
			"${SRCDIR}/public/bspflags.h"
			"${SRCDIR}/public/bumpvects.h"
			"${SRCDIR}/public/characterset.h"
			"${SRCDIR}/public/checksum_crc.h"
			"${SRCDIR}/public/client_class.h"
			"${SRCDIR}/public/client_textmessage.h"
			"${SRCDIR}/public/cmodel.h"
			"${SRCDIR}/public/collisionutils.h"
			"${SRCDIR}/public/Color.h"
			"${SRCDIR}/public/commonmacros.h"
			"${SRCDIR}/public/const.h"
			"${SRCDIR}/public/convar.h"
			"${SRCDIR}/public/coordsize.h"
			"${SRCDIR}/public/customentity.h"
			"${SRCDIR}/public/datamap.h"
			"${SRCDIR}/public/dlight.h"
			"${SRCDIR}/public/dt_common.h"
			"${SRCDIR}/public/dt_recv.h"
			"${SRCDIR}/public/dt_send.h"
			"${SRCDIR}/public/edict.h"
			"${SRCDIR}/public/editor_sendcommand.h"
			"${SRCDIR}/public/eiface.h"
			"${SRCDIR}/public/engine/icollideable.h"
			"${SRCDIR}/public/engine/IEngineSound.h"
			"${SRCDIR}/public/engine/IEngineTrace.h"
			"${SRCDIR}/public/engine/IStaticPropMgr.h"
			"${SRCDIR}/public/engine/ivmodelinfo.h"
			"${SRCDIR}/public/event_flags.h"
			"${SRCDIR}/public/filesystem.h"
			"${SRCDIR}/public/filesystem_helpers.h"
			"${SRCDIR}/public/fmtstr.h"
			"${SRCDIR}/public/gametrace.h"
			"${SRCDIR}/public/globalvars_base.h"
			"${SRCDIR}/public/icliententity.h"
			"${SRCDIR}/public/iclientnetworkable.h"
			"${SRCDIR}/public/iclientrenderable.h"
			"${SRCDIR}/public/iclientunknown.h"
			"${SRCDIR}/public/icvar.h"
			"${SRCDIR}/public/igameevents.h"
			"${SRCDIR}/public/igamemovement.h"
			"${SRCDIR}/public/ihandleentity.h"
			"${SRCDIR}/public/inetworkstringtableserver.h"
			"${SRCDIR}/public/interface.h"
			"${SRCDIR}/public/irecipientfilter.h"
			"${SRCDIR}/public/isaverestore.h"
			"${SRCDIR}/public/iserverentity.h"
			"${SRCDIR}/public/iservernetworkable.h"
			"${SRCDIR}/public/ispatialpartition.h"
			"${SRCDIR}/public/ivoiceserver.h"
			"${SRCDIR}/public/keyvalues.h"
			"${SRCDIR}/public/materialsystem/imaterial.h"
			"${SRCDIR}/public/materialsystem/imaterialvar.h"
			"${SRCDIR}/public/mathlib.h"
			"${SRCDIR}/public/measure_section.h"
			"${SRCDIR}/public/mempool.h"
			"${SRCDIR}/public/mem_fgets.h"
			"${SRCDIR}/public/model_types.h"
			"${SRCDIR}/public/networkstringtabledefs.h"
			"${SRCDIR}/public/networkvar.h"
			"${SRCDIR}/public/plane.h"
			"${SRCDIR}/public/PlayerState.h"
			"${SRCDIR}/public/processor_detect.h"
			"${SRCDIR}/public/protected_things.h"
			"${SRCDIR}/public/rope_physics.h"
			"${SRCDIR}/public/rope_shared.h"
			"${SRCDIR}/public/saverestoretypes.h"
			"${SRCDIR}/public/server_class.h"
			"${SRCDIR}/public/shake.h"
			"${SRCDIR}/public/shattersurfacetypes.h"
			"${SRCDIR}/public/simple_physics.h"
			"${SRCDIR}/public/soundflags.h"
			"${SRCDIR}/public/stringpool.h"
			"${SRCDIR}/public/stringregistry.h"
			"${SRCDIR}/public/string_t.h"
			"${SRCDIR}/public/studio.h"
			"${SRCDIR}/public/terrainmod.h"
			"${SRCDIR}/public/tier0/dbg.h"
			"${SRCDIR}/public/tier0/fasttimer.h"
			"${SRCDIR}/public/tier0/mem.h"
			"${SRCDIR}/public/tier0/memalloc.h"
			"${SRCDIR}/public/tier0/memdbgoff.h"
			"${SRCDIR}/public/tier0/memdbgon.h"
			"${SRCDIR}/public/tier0/platform.h"
			"${SRCDIR}/public/tier0/vprof.h"
			"${SRCDIR}/public/usercmd.h"
			"${SRCDIR}/public/utlbuffer.h"
			"${SRCDIR}/public/utldict.h"
			"${SRCDIR}/public/utllinkedlist.h"
			"${SRCDIR}/public/utlmap.h"
			"${SRCDIR}/public/utlmemory.h"
			"${SRCDIR}/public/utlpriorityqueue.h"
			"${SRCDIR}/public/utlrbtree.h"
			"${SRCDIR}/public/utlsymbol.h"
			"${SRCDIR}/public/utlvector.h"
			"${SRCDIR}/public/vallocator.h"
			"${SRCDIR}/public/vcollide.h"
			"${SRCDIR}/public/vcollide_parse.h"
			"${SRCDIR}/public/vector.h"
			"${SRCDIR}/public/vector2d.h"
			"${SRCDIR}/public/vector4d.h"
			"${SRCDIR}/public/vmatrix.h"
			"${SRCDIR}/public/vphysics/constraints.h"
			"${SRCDIR}/public/vphysics/vehicles.h"
			"${SRCDIR}/public/vphysics_interface.h"
			"${SRCDIR}/public/vplane.h"
			"${SRCDIR}/public/vstdlib/IKeyValuesSystem.h"
			"${SRCDIR}/public/vstdlib/random.h"
			"${SRCDIR}/public/vstdlib/strtools.h"
			"${SRCDIR}/public/vstdlib/vstdlib.h"
			"${SRCDIR}/public/worldsize.h"

			"actanimating.h"
			"ai_baseactor.h"
			"ai_basehumanoid.h"
			"ai_basehumanoid_movement.h"
			"ai_basenpc.h"
			"ai_basenpc_flyer.h"
			"ai_basenpc_flyer_new.h"
			"ai_basenpc_physicsflyer.h"
			"ai_behavior.h"
			"ai_behavior_assault.h"
			"ai_behavior_follow.h"
			"ai_behavior_lead.h"
			"ai_behavior_standoff.h"
			"ai_component.h"
			"ai_condition.h"
			"AI_Criteria.h"
			"ai_debug.h"
			"ai_default.h"
			"ai_dynamiclink.h"
			"ai_goalentity.h"
			"ai_hint.h"
			"ai_hull.h"
			"ai_initutils.h"
			"AI_Interest_Target.h"
			"ai_link.h"
			"ai_localnavigator.h"
			"ai_memory.h"
			"ai_motor.h"
			"ai_moveprobe.h"
			"ai_moveshoot.h"
			"ai_movesolver.h"
			"ai_movetypes.h"
			"ai_namespaces.h"
			"ai_navgoaltype.h"
			"ai_navigator.h"
			"ai_navtype.h"
			"ai_nav_property.h"
			"ai_network.h"
			"ai_networkmanager.h"
			"ai_node.h"
			"ai_npcstate.h"
			"ai_pathfinder.h"
			"ai_planesolver.h"
			"AI_ResponseSystem.h"
			"ai_route.h"
			"ai_routedist.h"
			"ai_saverestore.h"
			"ai_schedule.h"
			"ai_scriptconditions.h"
			"ai_senses.h"
			"ai_speech.h"
			"ai_squad.h" # !TF2
			"ai_squadslot.h"
			"ai_tacticalservices.h"
			"ai_task.h"
			"ai_trackpather.h"
			"ai_utils.h"
			"ai_waypoint.h"
			"baseanimating.h"
			"BaseAnimatingOverlay.h"
			"basecombatcharacter.h"
			"basecombatweapon.h"
			"baseentity.h"
			"baseflex.h"
			"basenetworkable.h"
			"BasePropDoor.h"
			"basetempentity.h"
			"basetoggle.h"
			"baseviewmodel.h"
			"base_transmit_proxy.h"
			"bitstring.h"
			"buttons.h"
			"cbase.h"
			"client.h"
			"cplane.h"
			"CRagdollMagnet.h" # !CSTRIKE && !HL1
			"damagemodifier.h"
			"doors.h"
			"enginecallback.h"
			"entityapi.h"
			"EntityFlame.h" # !CSTRIKE && !HL1
			"entityinput.h"
			"entitylist.h"
			"entitymapdata.h"
			"entityoutput.h"
			"EnvLaser.h"
			"EnvMessage.h"
			"envmicrophone.h"
			"eventlog.h"
			"eventqueue.h"
			"event_tempentity_tester.h"
			"explode.h"
			"filters.h"
			"fire.h"
			"fire_smoke.h"
			"fogcontroller.h"
			"fourwheelvehiclephysics.h"
			"func_areaportalbase.h"
			"func_areaportalwindow.h"
			"func_break.h"
			"func_breakablesurf.h"
			"func_movelinear.h"
			"game.h"
			"gameinterface.h"
			"gib.h"
			"globals.h"
			"globalstate.h"
			"globalstate_private.h"
			"grenadethrown.h" # !CSTRIKE
			"hierarchy.h"
			#"hl1_dll/hl1_weapon_handgrenade.h"
			"h_cycler.h" # !CSTRIKE && !HL1
			"ilagcompensationmanager.h"
			"init_factory.h"
			"iservervehicle.h"
			"items.h"
			"lights.h"
			"locksounds.h"
			"logicrelay.h"
			"mapentities.h"
			"maprules.h"
			"modelentities.h"
			"monstermaker.h" # !CSTRIKE && !HL2 && !HL1
			"movehelper_server.h"
			"movie_explosion.h"
			"ndebugoverlay.h"
			"netstatemgr.h"
			"networkstringtable_gamedll.h"
			"npc_talker.h"
			"particle_fire.h"
			"particle_light.h"
			"particle_smokegrenade.h"
			"physics.h"
			"physics_bone_follower.h" # !CSTRIKE && !HL1
			"physics_cannister.h"
			"physics_fx.h"
			"physics_impact_damage.h"
			"physics_prop_ragdoll.h"
			"physobj.h"
			"phys_controller.h"
			"player.h"
			"playerlocaldata.h"
			"player_command.h"
			"player_resource.h"
			"point_template.h"
			"props.h"
			"recipientfilter.h"
			"rope.h"
			"sceneentity.h"
			"scripted.h"
			"scriptedtarget.h"
			"sendproxy.h"
			"simtimer.h"
			"skycamera.h"
			"soundent.h"
			"soundscape.h"
			"splash.h"
			"team.h"
			"team_spawnpoint.h"
			"TemplateEntities.h"
			"terrainmodmgr.h"
			"test_stressentities.h"
			"textstatsmgr.h"
			"te_effect_dispatch.h"
			"trains.h"
			"triggers.h"
			"util.h"
			"variant_t.h"
			"vehicle_base.h" # !CSTRIKE && !TF2 && !HL1
			"vehicle_sounds.h"
			"vguiscreen.h"
			"wcedit.h"
			"winlite.h"
			"world.h"
		#}
	)
END_SRC( SERVER_BASE_HEADER_FILES "Header Files" )

function( target_use_server_base target EXCLUDE_SOURCES )

	set( USED_SOURCES ${SERVER_BASE_SOURCE_FILES} ${SERVER_BASE_HEADER_FILES} )

	if( ${EXCLUDE_SOURCES} )
		list( REMOVE_ITEM USED_SOURCES ${${EXCLUDE_SOURCES}} )
	endif()

	set_property( TARGET ${target} PROPERTY FOLDER "Game" )

	set_target_properties(
		${target} PROPERTIES

		LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/dlls/${target}"
		RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/dlls/${target}"
		ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/dlls/${target}"
	)

	target_sources( ${target} PRIVATE ${USED_SOURCES} )

	target_include_directories(
		${target} PRIVATE

		"${SRCDIR}/game_shared"
		"${SRCDIR}/utils/common"
		"${SRCDIR}/dlls"
	)

	target_compile_definitions(
		${target} PRIVATE

		"$<$<CONFIG:Debug>:fopen=dont_use_fopen>"
		GAME_DLL
		sprintf=use_Q_snprintf_instead_of_sprintf
		VECTOR
		strncpy=use_Q_strncpy_instead
		_snprintf=use_Q_snprintf_instead
		PROTECTED_THINGS_ENABLE
	)

	target_precompile_headers(
		${target} PRIVATE
		"cbase.h"
	)

endfunction()
