#=============================================================================
# groups.cmake
#
# Group Configurations for all Source(TM) Projects
#=============================================================================

if( ${BUILD_GROUP} STREQUAL "game" ) # everything what you need to run base game
	add_subdirectory( "Tracker/ServerBrowser" )
	add_subdirectory( "cl_dll" )
	add_subdirectory( "dlls" )
	add_subdirectory( "engine" )
	add_subdirectory( "engine/voice_codecs/miles" )
	add_subdirectory( "engine/voice_codecs/minimp3" )
	add_subdirectory( "filesystem" ) # filesystem_stdio, filesystem_steam
	add_subdirectory( "gameui" )
	add_subdirectory( "ivp/havana/havok/hk_base" )
	add_subdirectory( "ivp/havana/havok/hk_math" )
	add_subdirectory( "ivp/havana/havok/hk_physics/constraint" ) # havana_constraints
	add_subdirectory( "ivp/ivp_compact_builder" )
	add_subdirectory( "ivp/ivp_physics" )
	add_subdirectory( "launcher" )
	add_subdirectory( "launcher_main" )
	add_subdirectory( "materialsystem" )
	add_subdirectory( "materialsystem/shaderdx8" )
	add_subdirectory( "materialsystem/shaderempty" )
	add_subdirectory( "materialsystem/stdshaders" )
	add_subdirectory( "shaderlib" )
	add_subdirectory( "studiorender" )
	add_subdirectory( "tier0" )
	add_subdirectory( "vgui2/controls" )
	add_subdirectory( "vgui2/game_controls" )
	add_subdirectory( "vgui2/src" )
	add_subdirectory( "vgui2/vgui_surfacelib" )
	add_subdirectory( "vguimatsurface" )
	add_subdirectory( "vphysics" )
	add_subdirectory( "vstdlib" )
	add_subdirectory( "vtf" )
elseif( ${BUILD_GROUP} STREQUAL "dedicated" ) # dedicated server (SWDS)
	add_subdirectory( "dedicated" )
	add_subdirectory( "dlls" )
	add_subdirectory( "engine" )
	add_subdirectory( "filesystem" ) # filesystem_stdio, filesystem_steam
	add_subdirectory( "ivp/havana/havok/hk_base" )
	add_subdirectory( "ivp/havana/havok/hk_math" )
	add_subdirectory( "ivp/havana/havok/hk_physics/constraint" ) # havana_constraints
	add_subdirectory( "ivp/ivp_compact_builder" )
	add_subdirectory( "ivp/ivp_physics" )
	add_subdirectory( "materialsystem" )
	add_subdirectory( "materialsystem/shaderempty" )
	add_subdirectory( "studiorender" )
	add_subdirectory( "shaderlib" )
	add_subdirectory( "tier0" )
	add_subdirectory( "unitlib" )
	add_subdirectory( "vphysics" )
	add_subdirectory( "vstdlib" )
	add_subdirectory( "vtf" )
elseif( ${BUILD_GROUP} STREQUAL "everything" ) # every single item
	#add_subdirectory( "Tracker/AdminServer" )
	#add_subdirectory( "Tracker/Browser" )
	add_subdirectory( "Tracker/ServerBrowser" )
	#add_subdirectory( "Tracker/ServerMonitor" )
	#add_subdirectory( "Tracker/sqldb_mysql" )
	#add_subdirectory( "Tracker/sqldb_sqlite" )
	add_subdirectory( "Tracker/TrackerDBG" )
	add_subdirectory( "Tracker/TrackerNET" )
	add_subdirectory( "Tracker/TrackerSRV" )
	add_subdirectory( "Tracker/TrackerServer" )
	#add_subdirectory( "Tracker/TrackerTest" )
	add_subdirectory( "Tracker/TrackerUI" )
	add_subdirectory( "Tracker/TrackerVGUI" )
	#add_subdirectory( "Tracker/hlds_gui" )
	add_subdirectory( "appframework" )
	add_subdirectory( "cl_dll" )
	add_subdirectory( "dedicated" )
	add_subdirectory( "dlls" )
	add_subdirectory( "engine" )
	add_subdirectory( "engine/voice_codecs/miles" )
	add_subdirectory( "engine/voice_codecs/minimp3" )
	add_subdirectory( "filesystem" ) # filesystem_stdio, filesystem_steam
	add_subdirectory( "gameui" )
	add_subdirectory( "ivp/havana/havok/hk_base" )
	add_subdirectory( "ivp/havana/havok/hk_math" )
	add_subdirectory( "ivp/havana/havok/hk_physics/constraint" ) # havana_constraints
	add_subdirectory( "ivp/ivp_compact_builder" )
	add_subdirectory( "ivp/ivp_physics" )
	add_subdirectory( "launcher" )
	add_subdirectory( "launcher_main" )
	add_subdirectory( "master" )
	add_subdirectory( "master/hlmodmaster" )
	add_subdirectory( "master/mastertest" )
	add_subdirectory( "materialsystem" )
	add_subdirectory( "materialsystem/shaderdx8" )
	add_subdirectory( "materialsystem/shaderempty" )
	add_subdirectory( "materialsystem/stdshaders" )
	add_subdirectory( "shaderlib" )
	add_subdirectory( "status" )
	add_subdirectory( "studiorender" )
	add_subdirectory( "tier0" )
	add_subdirectory( "unitlib" )
	add_subdirectory( "utils/bsppack" )
	add_subdirectory( "utils/bspzip" )
	add_subdirectory( "utils/bugreporter" )
	add_subdirectory( "utils/classcheck" )
	add_subdirectory( "utils/glview" )
	add_subdirectory( "utils/height2normal" )
	add_subdirectory( "utils/hlfaceposer" )
	add_subdirectory( "utils/hlmviewer/src" )
	add_subdirectory( "utils/makels" )
	add_subdirectory( "utils/makevmt" )
	add_subdirectory( "utils/mdl35decompil" )
	#add_subdirectory( "utils/mysqlpp/vs2022" )
	add_subdirectory( "utils/mxtk/msvc" )
	add_subdirectory( "utils/newdat" )
	add_subdirectory( "utils/nvtristriplib" )
	add_subdirectory( "utils/phonemeextractor" )
	add_subdirectory( "utils/printbones" )
	add_subdirectory( "utils/printdummy1" )
	add_subdirectory( "utils/scenemanager" )
	add_subdirectory( "utils/studiomdl" )
	add_subdirectory( "utils/tgadiff" )
	add_subdirectory( "utils/unittest" )
	add_subdirectory( "utils/vbsp" )
	add_subdirectory( "utils/vbspinfo" )
	add_subdirectory( "utils/vgui_panel_zoo" )
	add_subdirectory( "utils/vmpi" )
	add_subdirectory( "utils/vmtedit" )
	add_subdirectory( "utils/vrad" )
	add_subdirectory( "utils/vrad_launcher" )
	add_subdirectory( "utils/vtex" )
	add_subdirectory( "utils/vtf2tga" )
	add_subdirectory( "utils/vtfdiff" )
	add_subdirectory( "utils/vvis" )
	add_subdirectory( "utils/vvis_launcher" )
	add_subdirectory( "vgui2/controls" )
	add_subdirectory( "vgui2/game_controls" )
	add_subdirectory( "vgui2/src" )
	add_subdirectory( "vgui2/vgui_surfacelib" )
	add_subdirectory( "vguimatsurface" )
	add_subdirectory( "vphysics" )
	add_subdirectory( "vstdlib" )
	add_subdirectory( "vtf" )
	add_subdirectory( "worldcraft" )
endif()
